----------------------------------------------------------------------------------------------------------------------
--insertion table address
-- ENTRY 1 --

INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (1, 1, 0, 1);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (2, 1, 0, 2);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (3, 1, 0, 3);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (4, 1, 1, 11);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (5, 1, 1, 12);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (6, 1, 1, 13);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (7, 1, 1, 14);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (8, 1, 2, 21);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (9, 1, 2, 22);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (10, 1, 2, 23);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (11, 1, 2, 24);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (12, 1, 3, 31);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (13, 1, 3, 32);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (14, 1, 3, 33);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (15, 1, 3, 34);

-- ENTRY 3 --

INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (16, 3, 0, 1);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (17, 3, 0, 2);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (18, 3, 0, 3);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (19, 3, 1, 11);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (20, 3, 1, 12);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (21, 3, 1, 13);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (22, 3, 1, 14);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (23, 3, 2, 21);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (24, 3, 2, 22);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (25, 3, 2, 23);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (26, 3, 2, 24);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (27, 3, 3, 31);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (28, 3, 3, 32);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (29, 3, 3, 33);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (30, 3, 3, 34);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (31, 3, 4, 41);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (32, 3, 4, 42);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (33, 3, 4, 43);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (34, 3, 4, 44);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (35, 3, 5, 51);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (36, 3, 5, 52);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (37, 3, 5, 53);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (38, 3, 5, 54);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (39, 3, 6, 61);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (40, 3, 6, 62);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (41, 3, 6, 63);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (42, 3, 6, 64);


-- ENTRY 5 --

INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (43, 5, 0, 1);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (44, 5, 0, 2);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (45, 5, 0, 3);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (46, 5, 1, 11);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (47, 5, 1, 12);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (48, 5, 1, 13);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (49, 5, 1, 14);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (50, 5, 2, 21);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (51, 5, 2, 22);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (52, 5, 2, 23);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (53, 5, 2, 24);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (54, 5, 3, 31);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (55, 5, 3, 32);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (56, 5, 3, 33);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (57, 5, 3, 34);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (58, 5, 4, 41);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (59, 5, 4, 42);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (60, 5, 4, 43);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (61, 5, 4, 44);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (62, 5, 5, 51);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (63, 5, 5, 52);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (64, 5, 5, 53);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (65, 5, 5, 54);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (66, 5, 6, 61);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (67, 5, 6, 62);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (68, 5, 6, 63);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (69, 5, 6, 64);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (70, 5, 7, 71);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (71, 5, 7, 72);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (72, 5, 7, 73);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (73, 5, 7, 74);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (74, 5, 8, 81);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (75, 5, 8, 82);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (76, 5, 8, 83);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (77, 5, 8, 84);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (78, 5, 9, 91);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (79, 5, 9, 92);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (80, 5, 9, 93);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (81, 5, 9, 94);

-- ENTRY 7 --

INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (82, 7, 0, 1);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (83, 7, 0, 2);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (84, 7, 0, 3);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (85, 7, 1, 11);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (86, 7, 1, 12);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (87, 7, 1, 13);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (88, 7, 1, 14);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (89, 7, 2, 21);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (90, 7, 2, 22);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (91, 7, 2, 23);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (92, 7, 2, 24);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (93, 7, 3, 31);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (94, 7, 3, 32);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (95, 7, 3, 33);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (96, 7, 3, 34);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (97, 7, 4, 41);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (98, 7, 4, 42);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (99, 7, 4, 43);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (100, 7, 4, 44);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (101, 7, 5, 51);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (102, 7, 5, 52);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (103, 7, 5, 53);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (104, 7, 5, 54);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (105, 7, 6, 61);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (106, 7, 6, 62);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (107, 7, 6, 63);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (108, 7, 6, 64);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (109, 7, 7, 71);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (110, 7, 7, 72);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (111, 7, 7, 73);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (112, 7, 7, 74);

-- ENTRY 9 --

INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (113, 9, 0, 1);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (114, 9, 0, 2);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (115, 9, 0, 3);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (116, 9, 1, 11);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (117, 9, 1, 12);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (118, 9, 1, 13);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (119, 9, 1, 14);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (120, 9, 2, 21);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (121, 9, 2, 22);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (122, 9, 2, 23);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (123, 9, 2, 24);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (124, 9, 3, 31);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (125, 9, 3, 32);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (126, 9, 3, 33);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (127, 9, 3, 34);

-- ENTRY 11 --

INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (128, 11, 0, 1);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (129, 11, 0, 2);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (130, 11, 0, 3);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (131, 11, 1, 11);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (132, 11, 1, 12);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (133, 11, 1, 13);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (134, 11, 1, 14);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (135, 11, 2, 21);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (136, 11, 2, 22);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (137, 11, 2, 23);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (138, 11, 2, 24);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (139, 11, 3, 31);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (140, 11, 3, 32);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (141, 11, 3, 33);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (142, 11, 3, 34);

-- ENTRY 13 --

INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (143, 13, 0, 1);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (144, 13, 0, 2);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (145, 13, 0, 3);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (146, 13, 1, 11);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (147, 13, 1, 12);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (148, 13, 1, 13);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (149, 13, 1, 14);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (150, 13, 2, 21);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (151, 13, 2, 22);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (152, 13, 2, 23);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (153, 13, 2, 24);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (154, 13, 3, 31);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (155, 13, 3, 32);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (156, 13, 3, 33);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (157, 13, 3, 34);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (158, 13, 4, 41);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (159, 13, 4, 42);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (160, 13, 4, 43);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (161, 13, 4, 44);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (162, 13, 5, 51);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (163, 13, 5, 52);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (164, 13, 5, 53);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (165, 13, 5, 54);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (166, 13, 6, 61);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (167, 13, 6, 62);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (168, 13, 6, 63);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (169, 13, 6, 64);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (170, 13, 7, 71);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (171, 13, 7, 72);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (172, 13, 7, 73);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (173, 13, 7, 74);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (174, 13, 8, 81);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (175, 13, 8, 82);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (176, 13, 8, 83);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (177, 13, 8, 84);

-- ENTRY 15 --

INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (178, 15, 0, 1);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (179, 15, 0, 2);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (180, 15, 0, 3);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (181, 15, 1, 11);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (182, 15, 1, 12);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (183, 15, 1, 13);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (184, 15, 1, 14);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (185, 15, 2, 21);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (186, 15, 2, 22);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (187, 15, 2, 23);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (188, 15, 2, 24);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (189, 15, 3, 31);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (190, 15, 3, 32);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (191, 15, 3, 33);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (192, 15, 3, 34);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (193, 15, 4, 41);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (194, 15, 4, 42);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (195, 15, 4, 43);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (196, 15, 4, 44);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (197, 15, 5, 51);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (198, 15, 5, 52);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (199, 15, 5, 53);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (200, 15, 5, 54);

-- ENTRY 17 --

INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (201, 17, 0, 1);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (202, 17, 0, 2);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (203, 17, 0, 3);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (204, 17, 1, 11);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (205, 17, 1, 12);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (206, 17, 1, 13);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (207, 17, 1, 14);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (208, 17, 2, 21);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (209, 17, 2, 22);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (210, 17, 2, 23);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (211, 17, 2, 24);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (212, 17, 3, 31);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (213, 17, 3, 32);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (214, 17, 3, 33);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (215, 17, 3, 34);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (216, 17, 4, 41);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (217, 17, 4, 42);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (218, 17, 4, 43);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (219, 17, 4, 44);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (220, 17, 5, 51);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (221, 17, 5, 52);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (223, 17, 5, 53);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (224, 17, 5, 54);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (225, 17, 6, 61);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (226, 17, 6, 62);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (227, 17, 6, 63);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (228, 17, 6, 64);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (229, 17, 7, 71);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (230, 17, 7, 72);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (231, 17, 7, 73);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (232, 17, 7, 74);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (234, 17, 8, 81);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (235, 17, 8, 82);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (236, 17, 8, 83);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (237, 17, 8, 84);

-- ENTRY 19 --

INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (238, 19, 0, 1);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (239, 19, 0, 2);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (240, 19, 0, 3);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (241, 19, 1, 11);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (242, 19, 1, 12);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (243, 19, 1, 13);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (244, 19, 1, 14);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (245, 19, 2, 21);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (246, 19, 2, 22);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (247, 19, 2, 23);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (248, 19, 2, 24);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (249, 19, 3, 31);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (250, 19, 3, 32);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (251, 19, 3, 33);
INSERT INTO ASSOCIATION.T_R_ADDRESS_ADS(ADS_ID, ADS_ENTRY, ADS_FLOOR, ADS_APARTMENT)
VALUES (252, 19, 3, 34);


INSERT INTO AUTHENTICATION.T_R_ROLE_RLE(rle_id, rle_name, rle_created_at, rle_updated_at)
VALUES (NEXTVAL('AUTHENTICATION.T_R_ROLE_RLE_ID_SEQ'), 'ADMIN', now(), now());
INSERT INTO AUTHENTICATION.T_R_ROLE_RLE(rle_id, rle_name, rle_created_at, rle_updated_at)
VALUES (NEXTVAL('AUTHENTICATION.T_R_ROLE_RLE_ID_SEQ'), 'BOARD_MEMBER', now(), now());
INSERT INTO AUTHENTICATION.T_R_ROLE_RLE(rle_id, rle_name, rle_created_at, rle_updated_at)
VALUES (NEXTVAL('AUTHENTICATION.T_R_ROLE_RLE_ID_SEQ'), 'TENANT', now(), now());